/*

Given below are some properties of constructors.

1. it should be declared in public section of the class
2. They are automatically invoked whenever the object is created.
3. constructor do not return anything hence they dont have a return type
4. constructor have the same name as of the class.
5. It can have default params.
6. We cannot refer to the address.

*/




/*
Types of Constructor.

1.default
2.parameterized
*/
